---
new_page_extension: md
auto_deploy: true
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: ''
  label: Pages
  create: all
  match: "*.kr.md"
  new_doc_ext: app
- type: directory
  path: content/posts
  label: Posts
  create: all
  match: "**/*.kr.md"
  new_doc_ext: kr.md
- type: heading
  label: 한국어
- type: directory
  path: content/posts
  label: Posts
  create: all
  match: "**/*.en.md"
  new_doc_ext: en.md
- type: heading
  label: English
- type: document
  path: FORESTRY-README.md
  label: Welcome - First Steps
  read_only: true
- type: jekyll-posts
  label: Posts
  create: all
- type: directory
  path: ''
  label: Pages
  create: all
  match: "*.en.md"
  exclude: "*README.md"
  new_doc_ext: en.md
- type: document
  path: _config.yml
  label: Config
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: true
file_template: ":year:/:month:/:day:/:filename:"
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: _site
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: forestryio/ruby:2.6
  mount_path: "/srv"
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    --port 8080 --host 0.0.0.0 -d _site
